trigger:
- main 

pool: Self
# vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    steps:
    - checkout: self

    - script: |
        docker bild -t my-cc-app .
      displayName: 'Build Docker Image'
      
    - script: |
        docker tag my-cc-app arf21.jfrog.io/arf-docker/my-cc-app:v4
        docker login arf21.jfrog.io -u arfaat.tamboli@unisys.com -p AKCpBrvb13G9vALPp3rV4hrzfzBQ4jeFys9YeHdxw7iwmeJRNLat9y3jm6H4MJfcxo8qADTZ6
      displayName: 'Authenticate Login'
      
    - script: |
        docker push arf21.jfrog.io/arf-docker/my-cc-app:v4
      displayName: 'Push Docker Image'
    - task: CreateBug@2
      inputs:
        isyamlpipeline: true
        custompaths: true
        areapath: 'PipelineEg'
        iterationpath: 'PipelineEg\Sprint 1'
        customrequestor: false
      condition: failed()
      env:
        SYSTEM_ACCESSTOKEN: wahmw2omm3dlapvxhyxsdrgtl5w5p7omo2qyf7iacdwwe7whfjhq
