trigger:
- main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'runtime'
      version: '3.11.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      docker build -t my-cc-app .
      docker tag my-cc-app arf21.jfrog.io/arf-docker/my-cc-app:latest
      docker login arf21.jfrog.io -u arfaat.tamboli@unisys.com -p AKCpBrvb13G9vALPp3rV4hrzfzBQ4jeFys9YeHdxw7iwmeJRNLat9y3jm6H4MJfcxo8qADTZ6
      docker push arf21.jfrog.io/arf-docker/my-cc-app:latest
    displayName: 'Build and Push Docker Image'
