apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondemo
  labels:
    app: pythondemo
    tier: frontend
    kube-monkey/enabled: "enabled"              # Enable termination of this deployment
    kube-monkey/identifier: monkey-victim    # Custom name for our target
    kube-monkey/mtbf: "1"                       # Average number of days between targeting one of these pods
    kube-monkey/kill-mode: "fixed" # The killing method
    kube-monkey/kill-value: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythondemo
  template:
    metadata:
      labels:
        app: pythondemo
        tier: frontend
        kube-monkey/enabled: "enabled"              # Enable termination of this deployment
        kube-monkey/identifier: monkey-victim
    spec:
        containers:
          - name: pythondemo
            image: appimages
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
        imagePullSecrets:
          - name: secretsz
        nodeSelector:
          kubernetes.io/os: linux
---

apiVersion: v1 
kind: Service 
metadata: 
  name: pythondemo
spec: 
  selector: 
    app: pythondemo 
  ports: 
  - protocol: TCP 
    port: 5000
    targetPort: 8080
  type: LoadBalancer



    
